apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: linkerd
spec:
  vault:
    # References pki role
    path: pki_int/root/sign-intermediate
    server: http://10.110.251.131:8200
    auth:
      kubernetes:
        # References kubernetes auth role
        role: linkerd-vault-issuer
        mountPath: /v1/auth/kubernetes
        serviceAccountRef:
          name: vault-issuer
