repositories:
  - name: harbor
    url: https://helm.goharbor.io

releases:
  - name: harbor
    namespace: harbor
    chart: harbor/harbor
    version: 1.14.0
    values:
      - ../kubernetes/harbor/default-values.yml
      - ../kubernetes/harbor/values.yml
