repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus
    namespace: kunipas
    chart: prometheus-community/prometheus
    version: 25.11.0
    values:
      - ../kubernetes/prometheus/default-values.yml
