apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: loki-bucket-secret
  namespace: logging
spec:
  type: kv-v2
  # mount path
  mount: kunipas
  # path of the secret
  path: minio/admin
  # dest k8s secret
  destination:
    create: true
    name: vso-loki-bucket-secret
    transformation:
      excludeRaw: true
      templates:
        S3_LOKI_ACCESS_KEY_ID:
          text: |-
            {{- range $key, $value := .Secrets }}
            {{- if eq $key "MINIO_ROOT_USER"  }}
            {{- printf "%s" $value  -}}
            {{- end }}
            {{- end }}
        S3_LOKI_SECRET_ACCESS_KEY:
          text: |-
            {{- range $key, $value := .Secrets }}
            {{- if eq $key "MINIO_ROOT_PASSWORD"  }}
            {{- printf "%s" $value  -}}
            {{- end }}
            {{- end }}
      excludes:
        - .*
  hmacSecretData: true
  # static secret refresh interval
  refreshAfter: 30s
  # Name of the CRD to authenticate to Vault
  vaultAuthRef: kunipas-loki
