---
- name: Start Traefik
  when: traefik_enabled is true
  block:
    - name: Create Traefik Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ traefik_data_directory }}"
        - "{{ traefik_data_directory }}/letsencrypt"

    - name: Template Traefik config.yml
      ansible.builtin.template:
        src: traefik.yml
        dest: "{{ traefik_data_directory }}/traefik.yml"
      register: template_config

    - name: Traefik Docker Container
      community.docker.docker_container:
        name: "{{ traefik_container_name }}"
        image: "{{ traefik_image_name }}:{{ traefik_image_version }}"
        pull: true
        networks:
          - name: proxy
        ports:
          - 80:80
          - 443:443
          - 8083:8083
        # network_mode: host
        volumes:
          - "{{ traefik_data_directory }}/traefik.yml:/etc/traefik/traefik.yml:ro"
          - "{{ traefik_data_directory }}/letsencrypt:/letsencrypt:rw"
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
        env: "{{ traefik_environment_variables }}"
        restart_policy: unless-stopped
        memory: "{{ traefik_memory }}"
        recreate: "{{ template_config is changed }}"

- name: Stop Traefik
  when: traefik_enabled is false
  block:
    - name: Stop Traefik
      community.docker.docker_container:
        name: "{{ traefik_container_name }}"
        state: absent
