apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: prod-dns-cluster-issuer
  namespace: cert-manager
spec:
  acme:
    email: foo@example.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: prod-dns-cluster-issuer
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
