apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: kunipas-minio
  namespace: s3
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: kunipas-minio
    serviceAccount: vso-kunipas-minio
    audiences:
      - vault
