apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: kunipas-harbor
  namespace: harbor
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: kunipas-harbor
    serviceAccount: vso-kunipas-harbor
    audiences:
      - vault
