apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: kunipas-thanos
  namespace: monitoring
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: kunipas-thanos
    serviceAccount: vso-kunipas-thanos
    audiences:
      - vault
